# Generated by Django 2.1.3 on 2018-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatar/static/avatar_images'),
        ),
    ]
