# Generated by Django 2.1.3 on 2018-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_auto_20181107_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='static/avatar_images'),
        ),
    ]
