# Generated by Django 2.1.3 on 2018-11-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_auto_20181107_1702'),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iten',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.Avatar', verbose_name='Description'),
        ),
    ]
