# Generated by Django 2.1.3 on 2018-11-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_iten_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iten',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.Avatar', verbose_name='Description'),
        ),
    ]
