# Generated by Django 2.1.3 on 2018-11-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20181115_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='datetime_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_iten',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itens.Iten'),
        ),
    ]
